#!/usr/bin/env node

var parse = require('./parse');

var tests = require('postcss-parser-tests');
var path  = require('path');
var fs    = require('fs');

var dir = path.join(__dirname, 'test', 'cases');
fs.readdirSync(dir).filter(function (i) {
    return path.extname(i) === '.sss';
}).forEach(function (name) {
    var sssFile  = path.join(dir, name);
    var jsonFile = sssFile.replace(/\.sss/, '.json');
    var sss      = fs.readFileSync(sssFile).toString().trim();
    var root     = parse(sss, { from: name });
    fs.writeFileSync(jsonFile, tests.jsonify(root) + '\n');
});
