#!/usr/bin/env node

let parse = require('./parse')

let tests = require('postcss-parser-tests')
let path = require('path')
let fs = require('fs')

let dir = path.join(__dirname, 'test', 'cases')
fs.readdirSync(dir).filter(i => {
  return path.extname(i) === '.sss'
}).forEach(name => {
  let sssFile = path.join(dir, name)
  let cssFile = sssFile.replace(/\.sss/, '.css')
  let jsonFile = sssFile.replace(/\.sss/, '.json')
  let sss = fs.readFileSync(sssFile).toString()
  let root = parse(sss, { from: name })
  fs.writeFileSync(cssFile, root.toString())
  fs.writeFileSync(jsonFile, tests.jsonify(root) + '\n')
})
